FROM public.ecr.aws/lambda/python:3.12

COPY --from=ghcr.io/astral-sh/uv:0.6.7 /uv /bin/uv

COPY pyproject.toml .
RUN uv pip install --system --no-cache \
    "fastapi>=0.115.12" \
    "httpx>=0.28.1" \
    "pydantic-settings>=2.9.1" \
    "mangum>=0.19.0"

COPY app ./app

CMD ["app.handler.handler"]
